SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    /* 해당 연도(PARTITION) 내에서의 최대값 - 내 크기 */
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC;