SELECT      T.ID AS ID, T.FISH_NAME AS FISH_NAME, T.LENGTH AS LENGTH -- 서브쿼리의 컬럼은 가져올 수 없음.
FROM        (SELECT  I.ID, N.FISH_NAME, I.FISH_TYPE, I.LENGTH, 
             ROW_NUMBER() OVER (PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS RN
             FROM   FISH_INFO I 
             JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
             WHERE  I.LENGTH IS NOT NULL
            ) AS T
WHERE       RN = 1
ORDER BY    T.ID;